services:
  db-postgresql:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "teste"
    ports:
      - "15432:5432"
    volumes:
      - ./PostgreSQL:/var/lib/postgresql/data 
    networks:
      - postgres-compose-network
      
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "william@teste.com.br"
      PGADMIN_DEFAULT_PASSWORD: "teste"
    ports:
      - "16543:80"
    depends_on:
      - db-postgresql
    networks:
      - postgres-compose-network

networks: 
  postgres-compose-network:
    driver: bridge